//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garantiTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_marka
    {
        public int IND { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string MARKAADI { get; set; }
    
        public virtual tbl_cari tbl_cari { get; set; }
    }
}
