//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garantiTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cari()
        {
            this.tbl_marka = new HashSet<tbl_marka>();
        }
    
        public int IND { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public Nullable<int> YETKILI { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string VERGINO { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public Nullable<decimal> ISKONTO { get; set; }
        public Nullable<int> FIRMATIPI { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
        public string KOD5 { get; set; }
        public string ADI { get; set; }
        public string SOYAD { get; set; }
        public string UNVAN { get; set; }
        public Nullable<int> SEKTOR { get; set; }
        public Nullable<int> MARKA { get; set; }
        public string EMAIL { get; set; }
        public string URL { get; set; }
        public string TELEFON1 { get; set; }
        public string TELEFON2 { get; set; }
        public string ADRESFATURA { get; set; }
        public string ADRESSEVK { get; set; }
        public string PARABIRIMI { get; set; }
        public string IL { get; set; }
        public string SEHIR { get; set; }
        public Nullable<int> PERSONELNO { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> YETKİLİDGMTARİH { get; set; }
        public Nullable<int> HIZMETTURU { get; set; }
        public Nullable<int> BASBITTAR { get; set; }
        public Nullable<int> PersonelYorum { get; set; }
    
        public virtual tbl_baslangicBitisTarih tbl_baslangicBitisTarih { get; set; }
        public virtual tbl_firmaTipi tbl_firmaTipi { get; set; }
        public virtual tbl_hizmetturu tbl_hizmetturu { get; set; }
        public virtual tbl_personel tbl_personel { get; set; }
        public virtual tbl_sektor tbl_sektor { get; set; }
        public virtual tbl_status tbl_status { get; set; }
        public virtual tbl_Yetkili tbl_Yetkili { get; set; }
        public virtual tbl_yorum tbl_yorum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_marka> tbl_marka { get; set; }
    }
}
