//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garantiTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ariza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ariza()
        {
            this.tbl_cari = new HashSet<tbl_cari>();
        }
    
        public int IND { get; set; }
        public Nullable<int> CariID { get; set; }
        public string ArızaTanim { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public Nullable<int> GidilenServisSayisi { get; set; }
        public string ArizaKaynagi { get; set; }
        public Nullable<System.DateTime> EnSonGidilenServisTarih { get; set; }
        public Nullable<System.DateTime> MusteriKayitTarih { get; set; }
        public Nullable<System.DateTime> ArizaKayitTarih { get; set; }
        public string MusteriYorumu { get; set; }
        public string PersonelYorumu { get; set; }
        public Nullable<bool> MusteriAktifMi { get; set; }
        public string MusteriAldigiHizmet { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriAdres { get; set; }
        public string ArizaTür { get; set; }
        public string OnarimSüresi { get; set; }
        public string UrunTuru { get; set; }
        public Nullable<System.DateTime> IstenilenServisTarihi { get; set; }
        public string MusteriTuru { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cari> tbl_cari { get; set; }
    }
}
