//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garantiTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCari
    {
        public Nullable<int> Expr3 { get; set; }
        public string AD { get; set; }
        public int Expr4 { get; set; }
        public string Expr14 { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public Nullable<System.DateTime> DGMTARİH { get; set; }
        public Nullable<System.DateTime> BİTİSTARİH { get; set; }
        public Nullable<System.DateTime> BASLANGICTARİH { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public int Expr2 { get; set; }
        public int Expr5 { get; set; }
        public Nullable<int> Expr6 { get; set; }
        public Nullable<bool> Expr15 { get; set; }
        public int Expr7 { get; set; }
        public Nullable<int> Expr8 { get; set; }
        public string Expr16 { get; set; }
        public int Expr9 { get; set; }
        public Nullable<int> Expr10 { get; set; }
        public string Expr11 { get; set; }
        public int Expr17 { get; set; }
        public Nullable<int> FIRMANO { get; set; }
        public string FIRMATİPİ { get; set; }
        public int Expr12 { get; set; }
        public Nullable<int> Expr13 { get; set; }
        public string MARKAADI { get; set; }
        public int IND { get; set; }
        public string FIRMAKODU { get; set; }
        public string FIRMAADI { get; set; }
        public Nullable<int> YETKILI { get; set; }
        public string VERGIDAIRESI { get; set; }
        public string VERGINO { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public Nullable<decimal> ISKONTO { get; set; }
        public Nullable<int> FIRMATIPI { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public string KOD3 { get; set; }
        public string KOD4 { get; set; }
        public string KOD5 { get; set; }
        public string ADI { get; set; }
        public string SOYAD { get; set; }
        public string UNVAN { get; set; }
        public Nullable<int> SEKTOR { get; set; }
        public Nullable<int> MARKA { get; set; }
        public string EMAIL { get; set; }
        public string URL { get; set; }
        public string TELEFON1 { get; set; }
        public string TELEFON2 { get; set; }
        public string ADRESFATURA { get; set; }
        public string ADRESSEVK { get; set; }
        public string PARABIRIMI { get; set; }
        public string IL { get; set; }
        public string SEHIR { get; set; }
        public Nullable<int> PERSONELNO { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> YETKİLİDGMTARİH { get; set; }
        public Nullable<int> HIZMETTURU { get; set; }
        public Nullable<int> BASBITTAR { get; set; }
    }
}
